---
title: "Exploring the Opioid Crisis"
date: '2019-10-20'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=5,fig.height = 3.33)

```

## David Hein

### Introduction
This project explores the interaction of several different variables related to the ongoing opioid crisis in the United States. There were four different data sets combined. The data sets for opioid prescription rates per 100 people and drug overdose deaths per 100,000 people on a county level in 2016 were taken from the CDC. The data sets for median household income on a county level and percentage of adults lacking a high school diploma on a county level in 2016 were taken from the US Census Bureau. The expected association is that low income counties will have high levels of opioid prescription rates, drug overdose rates, and percentages of people without high school diplomas. 

### Loading Data & Packages
Income was being read in a factor, I had to turn it into a char. Later on in data cleaning I go through the process of finally turning it into an integer. 
```{R echo=T, results='hide', message=FALSE, warning=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=60)}
setwd("C:/Users/dave/Desktop/CompBioProject")
scriptrate <- read.csv("Opiod_Rates.csv")
income <- read.csv("finalincome.csv",stringsAsFactors = FALSE,header = TRUE)
deaths <- read.csv("Drug_poisoning.csv")
education <- read.csv("cleanededucation.csv")
library(dplyr)
library(tidyr)
library(tidyverse)
deaths <- as.data.frame(deaths)
library(lmtest)
library(pROC)
library(plotROC)
##loading packages and data
```


### Cleaning Data
The data set for drug deaths included almost thirty years worth of data thus had to be filtered to just 2016. The income data was stored as characters, thus had to be unlisted and changed to a numeric value, and then added back into the data frame. The drug deaths per 100,000 people was renamed to deathrate, the median income was renamed to newincome, the percentage without a highschool diploma was renamed to diplomaless, and the opioid prescription rate per 100 people was renamed prate. No reshaping was necessary as all data was properly formatted by the CDC and Census. Most data sets contained extraneous data thus select was used to grab only the data needed. I used separate quite a bit because I thought I would join by county name, but this proved to be not ideal as there were a lot of duplicates.  
```{R warning=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=60)}
sixteendeath <- deaths %>% filter(Year == 2016) %>% dplyr::select(FIPS,County,Model.based.Death.Rate) %>%
    separate(County, into=c("county","state"), sep = ",") %>% rename(deathrate = Model.based.Death.Rate) %>% dplyr::select(-county)

cincome <- income$incomes %>% unlist() %>% as.numeric()
totincome <- income %>% mutate(newincome=cincome)


ceducation <- education %>% dplyr::select(FIPS.Code, Area.name, Percent.of.adults.with.less.than.a.high.school.diploma..2013.17) %>%
  rename( diplomaless = Percent.of.adults.with.less.than.a.high.school.diploma..2013.17) %>% rename(county = Area.name) %>%
  rename(FIPS = FIPS.Code) %>% dplyr::select(-county)

cscriptrate <- scriptrate %>% separate(County, into=c("county","state"),sep = ",") %>% dplyr::select(county,Code,Rate,-state) %>%
  rename(FIPS = Code,prate = Rate) %>% drop_na(prate) %>% distinct()

##cleaning data
```


### Joining Data
The unique FIPS county code was used to join the data sets. There were a surprisingly large number of counties in different states with the same name, thus county name could not be used. I used inner joins to produce complete data sets with no missing data. About 250 counties were dropped, mostly because they lacked data on opioid prescription rates. 
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
educationandprate <- full_join(ceducation,cscriptrate, by = "FIPS")
almostfulldata <- inner_join(educationandprate, sixteendeath, by = "FIPS")
fulldata <- inner_join(almostfulldata,totincome,by="FIPS") %>% drop_na() %>% dplyr::select(-incomes)
glimpse(fulldata)
##Joining data
```


### Summary Stats
The state with the largest average drug overdose death rate was West Virgina, followed by Kentucky. Surprisingly, counties in Kentucky have on average more opioid prescriptions than people. I computed many state and national averages for the variables in this data set, but I think the correlation matrix is the most interesting by far. The correlation between median income and percentage people lacking a high school was strongly negative at -0.57 as would be expected. The correlation between death rate and prescription rate was 0.27 suggeting that with more opioids available people are more likely to overdose. There is also a negative correlation between prescription  rate and median income, suggesting that poor counties have more opioid prescriptions.
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
##state level
fulldata %>% group_by(state) %>% summarise(AveragePrate = mean(prate), MedianIncome = mean(newincome), AverageDeathRate=mean(deathrate)) %>% 
  arrange(desc(AverageDeathRate))

##national averages
fulldata %>% summarise(AveragePrate = mean(prate), MedianIncome = mean(newincome), 
                       AverageDeathRate=mean(deathrate),adultsnotgraduatedhigh = mean(diplomaless))


numericdata <- fulldata %>% dplyr::select_if(is.numeric) %>% dplyr::select(-FIPS)
cormatrix <- cor(numericdata)%>%as.data.frame%>%
  rownames_to_column%>%pivot_longer(-1)%>% ggplot(aes(rowname,name,fill=value))+geom_tile()+
  geom_text(aes(label=round(value,2)))+
  xlab("")+ylab("") + scale_fill_gradient2(low="red",high="green")
cormatrix
##some summary statistics
```


### County Level Graph of Drug Deaths vs Opioid Prescription with median income as fill
This graph shows the positive correlation between drug related deaths and opioid prescriptions. The blue high income counties tend to be located in the bottom left, indicating low deaths and prescription rates. 
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
numericdata <- fulldata %>% select_if(is.numeric) %>% dplyr::select(-FIPS)
ggplot(numericdata,aes(x=prate,y=deathrate,color=newincome)) + geom_point() + geom_smooth(method=lm) + 
  xlab("Opioid Prescription Rate per 100 People") +
   ylab("Drug Related Deaths per 100,000 People") + scale_color_gradient(low="red", high="blue") + theme_test()
##county level
```

### State Level Graph of Drug Deaths vs Opioid prescriptions with median income as fill
This graph shows the same positive correlation as the one before but uses summarized data of state averages. The correlation is not a strong when using state level data because there is less variation between states as a whole than there are between counties. 
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
fulldata %>% group_by(state) %>% summarise(AveragePrate = mean(prate), MedianIncome = mean(newincome), AverageDeathRate=mean(deathrate)) %>%
  ggplot(aes(x=AveragePrate,y=AverageDeathRate,color=MedianIncome)) + geom_point() + geom_smooth(method=lm) + 
  xlab("Opioid Prescription Rate per 100 People") +
  ylab("Drug Related Deaths per 100,000 People") + scale_color_gradient(low="red", high="blue") + theme_test()
##state level
```


### PCA
Principle component 1 describes 45% of variance in the data. This component separates high income counties from counties that have high rates of opioid prescriptions, drug deaths, and adults without high school diplomas. Basically, low income is positively correlated to the three other variables. Three principle components describe 89% of the variation. 
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
scaled <- numericdata %>% scale()
scaledpca <- princomp(scaled)
summary(scaledpca,loadings=T)
ggplot() + geom_point(aes(scaledpca$scores[,1],scaledpca$scores[,2]))+xlab("PC1")+ylab("PC2") + theme_test()
```


### Regression
In the logistic regression only the prescription rate term was significant. An increase in 1 prescription per 100 people increases the odds of a county being 1 standard deviation above the mean in drug overdose death rates by a factor of 1.011 (while controlling for other variables). The AUC for the roc plot was 0.65, suggesting this model is not a very good fit. The linear regression shows a significant effect of prescription rate and average income on death rate while controlling for other other variables. An increase in average income results in a decrease in death rates, and an increase in prescription rates results in an increase in death rates. The interaction term for prescription and adults without diplomas is significant. My working hypothesis for this is that communities with high populations of retired people may have high opioid prescriptions, high high-school diploma rates, and low drug overdose rates. Thus the effect of prescription rate on overdose deaths would differ across levels of diplomaless. 
```{R tidy=TRUE, tidy.opts=list(width.cutoff=60)}
#Making death rate a binary variable with 1 equal to a county with >1 std dev death rate above mean
meandeathrate <- mean(fulldata$deathrate)
stdevdeathrate <- sd(fulldata$deathrate)
cuttoff <- meandeathrate + stdevdeathrate
cuttoff

logdata <- fulldata %>% mutate(highdeaths = ifelse(deathrate>27.77,1,0))
fit <- glm(highdeaths~diplomaless+prate+newincome,data=logdata,family=binomial)
coeftest(fit)
exp(coef(fit))


probfit <- predict(fit,type="response")
rocplot<- ggplot(logdata) + geom_roc(aes(d = highdeaths, m = probfit),n.cuts=0) + theme_test()
rocplot
calc_auc(rocplot)


#A linear regression to look at the interaction of prate and diplomaless
fit2 <- glm(deathrate~prate*diplomaless+newincome,data=fulldata)
coeftest(fit2)

```


